#!/usr/bin/env bash

function _clojure_profile {
  local shome="${_clojure_home:="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/vendor/clojure/bin:$PATH"
}

_clojure_profile
