#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_clojure="0.0.1"
  jq -n --arg clojure "$ver_clojure" '{clojure: $clojure}'
}

version "$@"
