#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_clojure="$(clojure -Sverbose -e 1 2>/dev/null | awk '$1 == "version" { print $3 }' || true)"
  jq -n --arg clojure "$ver_clojure" '{clojure: $clojure}'
}

version "$@"
